#!/bin/bash
export ANSIBLE_HOST_KEY_CHECKING=False
ansible-playbook -vvv -i hosts ansible.yaml -e "SNOW_SECRET_KEY=$SNOW_SECRET_KEY SNOW_SQLALCHEMY_DATABASE_URI=$SNOW_SQLALCHEMY_DATABASE_URI SNOW_SQLALCHEMY_BINDS=$SNOW_SQLALCHEMY_BINDS SNOW_REDIS_URL=$SNOW_REDIS_URL image_tag=$IMAGE_TAG SNOW_COIN_URL=$SNOW_COIN_URL DOCKER_PASSWORD=$DOCKER_PASSWORD"

